apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: kubeschool-org-tls
spec:
  secretName: kubeschool-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.kubeschool.org'
  dnsNames:
    - '*.kubeschool.org'
    - kubeschool.org