apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: saurabh333/multi-container-client
        resources:
          requests:
            memory: "100Mi"
            cpu: "25m"
          limits:
            memory: "100Mi"
            cpu: "25m"
        ports:
        - containerPort: 3000
