apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-presisten-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
